function FrOut = read_FrOut133(fn)
% Extracts data from FREZCHEM v13.3 output file.
%
% Syntax:
% FrOut = read_FrOut133(fn)
%
% Inputs:
% fn        filename
%
% Outputs:
%
% FrOut     structure
%-----------Size-----------------------------------------------------------
%           N = number of temperature points
%           M = number of solution species
%           L = number of solid species
%
%-----------Bulk Properties (N x 1)----------------------------------------
%           FrOut.T                 Temperatures (K)
%           FrOut.ion_str           Ionic Strength
%           FrOut.rho_b             Brine Density (g/cm^3)
%           FrOut.osmotic_coef      Osmotic Coefficient
%           FrOut.br_H2O            Mass of Water in Brine (g)
%           FrOut.ice_H2O           Mass of Water in Ice (g)
%           FrOut.pressure          Pressure (bar)
%           FrOut.br_salt           Mass of Salt (Ions) in Brine (g)
%           FrOut.sm                Mass of Solid Salt (Hydrates) in Brine
%                                   (g)
%           FrOut.rho_ss            Total Density of Solid Salt (Hydrates)
%                                   (g/cm^3)
%           FrOut.H2O_activity      Water Activity
%
%-----------Solution Properties (N x M)------------------------------------
%           FrOut.solution_species  Solution Species (Ions)
%           FrOut.init_conc         Initial Concentration (moles/kg)
%           FrOut.final_conc        Final Concentration(moles/kg)
%           FrOut.activity_coef     Activity Coefficient
%           FrOut.activity          Activity
%           FrOut.solution_moles	Moles of Solution Species (moles)
%           FrOut.mass_balance      Mass of Major Species (moles/kg)
%
%-----------Solid Properties (N x L)---------------------------------------
%           FrOut.solid_species     Solid Species (Hydrates)
%           FrOut.solid_moles       Solid Moles (moles)
%           FrOut.equil_const       Equilibrium Constant
%           FrOut.accum_moles       Accumulated Moles (moles)
%
%-----------Salts Precipitating at the Eutectic (L* x 1)-------------------
% NOTE: This field will be populated with NaN if FREZCHEM does not reach
% the eutectic (sometimes it doesn't due to convergence issues).
%
%           FrOut.eutectic.T                Eutectic Temperature*
%           FrOut.eutectic.solid_species    Solid Species (Hydrates)
%                                           Precipitating at the Eutectic
%           FrOut.eutectic.fw               Weight Fraction Solid Salt
%                                           (Hydrates) Precipitating at
%                                           the Eutectic
%           FrOut.eutectic.rho_ss           Mean Density of Solid Salt
%                                           (Hydrates) Precipitating at
%                                           the Eutectic
%
% *If the eutectic temperature is defined as the lowest temperature at
% which melt can occur, this temperature corresponds to the temperature one
% step below that (i.e, where no melt is stable).
%
% Author:
% Natalie Wolfenbarger
% nswolfen@gmail.com
%
%% Elemental Properties (FREZCHEM)
elemental = load('element_properties.mat');
symb = elemental.Symbol;
mass = elemental.Atomic_Weight; % g/mol

% Species Number
species.num = [1:30,31:131,151:172]';
% solution/atmospheric species:   1 -  30
% solid species:                 31 - 131
% solution/atmospheric species: 151 - 172

% Species Name
species.str = {'NA';...
    'K';...
    'CA';...
    'MG';...
    'H';...
    'MGOH';...
    'FE';... % ++
    'FEOH';...
    'FE';... % +++
    'AL';...
    'CL';...
    'SO4';...
    'OH';...
    'HCO3';...
    'CO3';...
    'HSO4';...
    'NO3';...
    'BR';...
    'CLO4';...
    'B(OH)4';...
    'CO2';...
    'FECO3';...
    'HCL';...
    'CACO3';...
    'MGCO3';...
    'HNO3';...
    'H2SO4';...
    'H2O';...
    'CO2';...
    'H2O';...
    
    'ICE';...
    'NACL.2H2O';...
    'NACL';...
    'KCL';...
    'CACL2.6H2O';...
    'MGCL2.6H2O';...
    'MGCL2.8H2O';...
    'MGCL2.12H2O';...
    'KMGCL3.6H2O';...
    'CACL2.2MGCL2.12H2O';...
    'NA2SO4.10H2O';...
    'NA2SO4';...
    'MGSO4.6H2O';...
    'MGSO4.7H2O';...
    'K2SO4';...
    'MGSO4.K2SO4.6H2O';...
    'NA2SO4.MGSO4.4H2O';...
    'CASO4.2H2O';...
    'CASO4';...
    'MGSO4.11H2O';...
    'NA2SO4.3K2SO4';...
    'CACO3(CALCITE)';...
    'MGCO3';...
    'MGCO3.3H2O';...
    'MGCO3.5H2O';...
    'CACO3.6H2O';...
    'NAHCO3';...
    'NA2CO3.10H2O';...
    'NAHCO3.NA2CO3.2H2O';...
    '3MGCO3.MG(OH)2.3H2O';...
    'CAMG(CO3)2';...
    'NA2CO3.7H2O';...
    'KHCO3';...
    'CACO3(ARAGONITE)';...
    'CACO3(VATERITE)';...
    'HNO3.3H2O';...
    'KNO3';...
    'NANO3';...
    'HCL.3H2O';...
    'H2SO4.6.5H2O';...
    'H2SO4.4H2O';...
    'HCL.6H2O';...
    'NANO3.NA2SO4.2H2O';...
    'NA3H(SO4)2';...
    'NAHSO4.H2O';...
    'K3H(SO4)2';...
    'K5H3(SO4)4';...
    'K8H6(SO4)7.H2O';...
    'KHSO4';...
    'MGSO4.H2O';...
    'FESO4.7H2O';...
    'FESO4.H2O';...
    'FECL2.6H2O';...
    'FECL2.4H2O';...
    'FECO3';...
    'FE(OH)3';...
    'CO2.6H2O';...
    'CH4.6H2O';...
    'FECL3.10H20';...
    'FECL3.6H2O';...
    'FECL3.2KCL.H20';...
    'FE2(SO4)3';...
    'FE2(SO4)3.2K2SO4.14H';...
    'K2SO4.FESO4.6H2O';...
    'NA2SO4.FESO4.4H2O';...
    'FE2(SO4)3.9H2O';...
    'FE2(SO4)3.H2SO4.8H2O';...
    'KFE3(SO4)2(OH)6';...
    'NAFE3(SO4)2(OH)6';...
    'H3OFE3(SO4)2(OH)6';...
    'a-FE2O3';...
    'a-FEO(OH)';...
    'g-FEO(OH)';...
    'FEO(OH)3/4(SO4)1/8';...
    'FESO4.4H2O';...
    'FE2(SO4)3.7H2O';...
    'FE(II)FE(III)4(SO4)6';...
    'FE(III)5(SO4)6O(OH).';...
    'FE(II)FE(III)2(SO4)4';...
    'FE(II)FE(III)2(SO4)4';...
    'K2FE(II)5FE(III)4(SO';...
    'ALCL3.6H2O';...
    'AL2(SO4)3.17H2O';...
    'NABR';...
    'MGBR2';...
    'AL(OH)3';...
    'SIO2(QUARTZ)';...
    'SIO2(AMORPHOUS)';...
    'KAL3(SO4)2(OH)6';...
    'NAAL3(SO4)2(OH)6';...
    'KAL(SO4)2.12H2O';...
    'NAAL(SO4)2.12H2O';...
    'FESO4.AL2(SO4)3.22H2';...
    'AL2SI2O5(OH)4';...
    'MGSO4.AL2(SO4).22H2O';...
    'NACLO4.H2O';...
    'MG(CLO4)2.8H2O';...
    'CA(CLO4)2.6H2O';...
    'KCLO4';...
    'MG(CLO4)2.6H2O';...
    'NACLO4.2H2O';...
    
    'O2';... % (g)
    'O2';... % (aq)
    'H2';...
    'CH4';... % (g)
    'CH4';... % (aq)
    'FE(OH)2';...
    'FE(OH)3';... % -
    'FEOH';...
    'FE(OH)2';... % +
    'FE(OH)3';...
    'FE(OH)4';...
    'AL(OH)';...
    'AL(OH)2';...
    'AL(OH)3';...
    'AL(OH)4';...
    'SI(OH)4';...
    'SIO(OH)3';... % printed as SI(OH)3 in v13.3 documentation
    'N/A';...
    'B(OH)3';...
    'F';...
    'HF';...
    'SR'};

% Species Mass (g)
species.mass = ...
    [mass(strcmp('Na',symb));...    % (  1) Na
    mass(strcmp('K',symb));...      % (  2) K
    mass(strcmp('Ca',symb));...     % (  3) Ca
    mass(strcmp('Mg',symb));...     % (  4) Mg
    mass(strcmp('H',symb));...      % (  5) H
    mass(strcmp('Mg',symb))+...
    mass(strcmp('O',symb))+...
    mass(strcmp('H',symb));...      % (  6) MgOH
    mass(strcmp('Fe',symb));...     % (  7) Fe ++
    mass(strcmp('Fe',symb))+...
    mass(strcmp('O',symb))+...
    mass(strcmp('H',symb));...      % (  8) FeOH
    mass(strcmp('Fe',symb));...     % (  9) Fe +++
    mass(strcmp('Al',symb));...     % ( 10) Al
    mass(strcmp('Cl',symb));...     % ( 11) Cl
    mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb));...    % ( 12) SO4
    mass(strcmp('O',symb))+...
    mass(strcmp('H',symb));...      % ( 13) OH
    mass(strcmp('H',symb))+...
    mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb));...    % ( 14) HCO3
    mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb));...    % ( 15) CO3
    mass(strcmp('H',symb))+...
    mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb));...    % ( 16) HSO4
    mass(strcmp('N',symb))+...
    3*mass(strcmp('O',symb));...    % ( 17) NO3
    mass(strcmp('Br',symb));...     % ( 18) Br
    mass(strcmp('Cl',symb))+...
    4*mass(strcmp('O',symb));...    % ( 19) ClO4
    mass(strcmp('B',symb))+...
    4*(mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % ( 20) B(OH)4
    mass(strcmp('C',symb))+...
    2*mass(strcmp('O',symb));...    % ( 21) CO2
    mass(strcmp('Fe',symb))+...
    mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb));...    % ( 22) FeCO3
    mass(strcmp('H',symb))+...
    mass(strcmp('Cl',symb));...     % ( 23) HCl
    mass(strcmp('Ca',symb))+...
    mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb));...    % ( 24) CaCO3
    mass(strcmp('Mg',symb))+...
    mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb));...    % ( 25) MgCO3
    mass(strcmp('H',symb))+...
    mass(strcmp('N',symb))+...
    3*mass(strcmp('O',symb));...    % ( 26) HNO3 (g)
    2*mass(strcmp('H',symb))+...
    mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb));...    % ( 27) H2SO4 (g)
    2*mass(strcmp('H',symb))+...
    mass(strcmp('O',symb));...      % ( 28) H2O (g)
    mass(strcmp('C',symb))+...
    2*mass(strcmp('O',symb));...    % ( 29) CO2 (g)
    2*mass(strcmp('H',symb))+...
    mass(strcmp('O',symb));...      % ( 30) H2O
    2*mass(strcmp('H',symb))+mass(strcmp('O',symb));...    % ( 31) H2O
    mass(strcmp('Na',symb))+mass(strcmp('Cl',symb))+...
    2*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 32) NaCl-2H2O
    mass(strcmp('Na',symb))+mass(strcmp('Cl',symb));...     % ( 33) NaCl
    mass(strcmp('K',symb))+mass(strcmp('Cl',symb));...      % ( 34) KCl
    mass(strcmp('Ca',symb))+2*mass(strcmp('Cl',symb))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 35) CaCl2-6H2O
    mass(strcmp('Mg',symb))+2*mass(strcmp('Cl',symb))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 36) MgCl2-6H2O
    mass(strcmp('Mg',symb))+2*mass(strcmp('Cl',symb))+...
    8*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 37) MgCl2-8H2O
    mass(strcmp('Mg',symb))+2*mass(strcmp('Cl',symb))+...
    12*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% ( 38) MgCl2-12H2O
    mass(strcmp('K',symb))+mass(strcmp('Mg',symb))+...
    3*mass(strcmp('Cl',symb))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 39) KMgCl3-6H2O
    mass(strcmp('Ca',symb))+2*mass(strcmp('Cl',symb))+...
    2*(mass(strcmp('Mg',symb))+2*mass(strcmp('Cl',symb)))+...
    12*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% ( 40) CaCl2-2(MgCl2)-12H2O
    2*mass(strcmp('Na',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    10*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% ( 41) Na2SO4-10H2O
    2*mass(strcmp('Na',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb));...                            % ( 42) Na2SO4
    mass(strcmp('Mg',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 43) MgSO4-6H2O
    mass(strcmp('Mg',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    7*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 44) MgSO4-7H2O
    2*mass(strcmp('K',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb));...                            % ( 45) K2SO4
    mass(strcmp('Mg',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    2*mass(strcmp('K',symb))+mass(strcmp('S',symb))+4*mass(strcmp('O',symb))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 46) MgSO4-K2SO4-6H2O
    2*mass(strcmp('Na',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    mass(strcmp('Mg',symb))+mass(strcmp('S',symb))+4*mass(strcmp('O',symb))+...
    4*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 47) Na2SO4-MgSO4-4H2O
    mass(strcmp('Ca',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    2*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 48) CaSO4-2H2O
    mass(strcmp('Ca',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb));...                            % ( 49) CaSO4
    mass(strcmp('Mg',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    11*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% ( 50) MgSO4-11H2O
    2*mass(strcmp('Na',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    3*(2*mass(strcmp('K',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb)));...                           % ( 51) Na2SO4-3K2SO4
    mass(strcmp('Ca',symb))+...
    mass(strcmp('C',symb))+3*mass(strcmp('O',symb));...     % ( 52) CaCO3
    mass(strcmp('Mg',symb))+mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb));...                            % ( 53) MgCO3
    mass(strcmp('Mg',symb))+mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb))+...
    3*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 54) MgCO3-3H2O
    mass(strcmp('Mg',symb))+mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb))+...
    5*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 55) MgCO3-5H2O
    mass(strcmp('Ca',symb))+mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 56) CaCO3-6H2O
    mass(strcmp('Na',symb))+mass(strcmp('H',symb))+...
    mass(strcmp('C',symb))+3*mass(strcmp('O',symb));...     % ( 57) NaHCO3
    2*mass(strcmp('Na',symb))+mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb))+...
    10*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% ( 58) Na2CO3-10H2O
    mass(strcmp('Na',symb))+mass(strcmp('H',symb))+...
    mass(strcmp('C',symb))+3*mass(strcmp('O',symb))+...
    2*mass(strcmp('Na',symb))+mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb))+...
    2*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 59) NaHCO3-Na2CO3-2H2O
    3*(mass(strcmp('Mg',symb))+mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb)))+...
    mass(strcmp('Mg',symb))+2*(mass(strcmp('O',symb))+mass(strcmp('H',symb)))+...
    3*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 60) 3(MgCO3)Mg-2(OH)-3H2O
    mass(strcmp('Ca',symb))+mass(strcmp('Mg',symb))+...
    2*(mass(strcmp('C',symb))+3*mass(strcmp('O',symb)));... % ( 61) CaMg-2(CO3)
    2*mass(strcmp('Na',symb))+mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb))+...
    7*(mass(strcmp('H',symb))+2*mass(strcmp('O',symb)));... % ( 62) Na2CO3-7H2O
    mass(strcmp('K',symb))+mass(strcmp('H',symb))+...
    mass(strcmp('C',symb))+3*mass(strcmp('O',symb));...     % ( 63) KHCO3
    mass(strcmp('Ca',symb))+mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb));...                            % ( 64) CaCO3
    mass(strcmp('Ca',symb))+mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb));...                            % ( 65) CaCO3
    mass(strcmp('H',symb))+mass(strcmp('N',symb))+...
    3*mass(strcmp('O',symb))+...
    3*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 66) HNO3-3H2O
    mass(strcmp('K',symb))+mass(strcmp('N',symb))+...
    3*mass(strcmp('O',symb));...                            % ( 67) KNO3
    mass(strcmp('Na',symb))+mass(strcmp('N',symb))+...
    3*mass(strcmp('O',symb));...                            % ( 68) NaNO3
    mass(strcmp('H',symb))+mass(strcmp('Cl',symb))+...
    3*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 69) HCl-3H2O
    2*mass(strcmp('H',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    6.5*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% ( 70) H2SO4-6.5H2O
    2*mass(strcmp('H',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    4*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 71) H2SO4-4H2O
    mass(strcmp('H',symb))+mass(strcmp('Cl',symb))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 72) HCl-6H2O
    mass(strcmp('Na',symb))+mass(strcmp('N',symb))+...
    3*mass(strcmp('O',symb))+...
    2*mass(strcmp('Na',symb))+mass(strcmp('S',symb))+4*mass(strcmp('O',symb))+...
    2*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 73) NaNO3-Na2SO4-2H2O
    3*mass(strcmp('Na',symb))+mass(strcmp('H',symb))+...
    2*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)));... % ( 74) Na3H(SO4)2
    mass(strcmp('Na',symb))+mass(strcmp('H',symb))+...
    mass(strcmp('S',symb))+4*mass(strcmp('O',symb))+...
    2*mass(strcmp('H',symb))+mass(strcmp('O',symb));...     % ( 75) NaHSO4-H2O
    3*mass(strcmp('K',symb))+mass(strcmp('H',symb))+...
    2*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)));... % ( 76) K3H(SO4)2
    5*mass(strcmp('K',symb))+3*mass(strcmp('H',symb))+...
    4*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)));... % ( 77) K5H3(SO4)4
    8*mass(strcmp('K',symb))+6*mass(strcmp('H',symb))+...
    7*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    2*mass(strcmp('H',symb))+mass(strcmp('O',symb));...     % ( 78) K8H6(SO4)7-H2O
    mass(strcmp('K',symb))+mass(strcmp('H',symb))+...
    mass(strcmp('S',symb))+4*mass(strcmp('O',symb));...     % ( 79) KHSO4
    mass(strcmp('Mg',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    2*mass(strcmp('H',symb))+mass(strcmp('O',symb));...     % ( 80) MgSO4-H2O
    mass(strcmp('Fe',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    7*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 81) FeSO4-7(H2O)
    mass(strcmp('Fe',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    2*mass(strcmp('H',symb))+mass(strcmp('O',symb));...     % ( 82) FeSO4-H2O
    mass(strcmp('Fe',symb))+2*mass(strcmp('Cl',symb))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 83) FeCl2-6H2O
    mass(strcmp('Fe',symb))+2*mass(strcmp('Cl',symb))+...
    4*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 84) FeCl2-4H2O
    mass(strcmp('Fe',symb))+mass(strcmp('C',symb))+...
    3*mass(strcmp('O',symb));...                            % ( 85) FeCO3
    mass(strcmp('Fe',symb))+3*(mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...                             % ( 86) Fe(OH)3
    mass(strcmp('C',symb))+2*mass(strcmp('O',symb))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 87) CO2-6(H2O)
    mass(strcmp('C',symb))+4*mass(strcmp('H',symb))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 88) CH4-6(H2O)
    mass(strcmp('Fe',symb))+3*mass(strcmp('Cl',symb))+...
    10*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% ( 89) FeCl3-10H2O
    mass(strcmp('Fe',symb))+3*mass(strcmp('Cl',symb))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 90) FeCl3-6H2O
    mass(strcmp('Fe',symb))+3*mass(strcmp('Cl',symb))+...
    2*(mass(strcmp('K',symb))+mass(strcmp('Cl',symb)))+...
    2*mass(strcmp('H',symb))+mass(strcmp('O',symb));...     % ( 91) FeCl3-2KCl-H2O
    2*mass(strcmp('Fe',symb))+3*(mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb)));...                           % ( 92) Fe2(SO4)3
    2*mass(strcmp('Fe',symb))+3*(mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb)))+...
    2*(2*mass(strcmp('K',symb))+mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    14*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% ( 93) Fe2(SO4)3-2(K2SO4)14H2O
    2*mass(strcmp('K',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    mass(strcmp('Fe',symb))+mass(strcmp('S',symb))+4*mass(strcmp('O',symb))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 94) K2SO4FeSO46H2O
    2*mass(strcmp('Na',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    mass(strcmp('Fe',symb))+mass(strcmp('S',symb))+4*mass(strcmp('O',symb))+...
    4*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 95) Na2SO4FeSO4-4H2O
    2*mass(strcmp('Fe',symb))+3*(mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb)))+...
    9*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 96) Fe2(SO4)3-9H2O
    2*mass(strcmp('Fe',symb))+3*(mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb)))+...
    2*mass(strcmp('H',symb))+mass(strcmp('S',symb))+4*mass(strcmp('O',symb))+...
    8*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % ( 97) Fe2(SO4)3-H2SO4-8H2O
    mass(strcmp('K',symb))+3*mass(strcmp('Fe',symb))+...
    2*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    6*(mass(strcmp('O',symb))+mass(strcmp('H',symb)));...   % ( 98) KFe3-(SO4)2-6(OH)
    mass(strcmp('Na',symb))+3*mass(strcmp('Fe',symb))+...
    2*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    6*(mass(strcmp('O',symb))+mass(strcmp('H',symb)));...   % ( 99) NaFe3(SO4)2-6(OH)
    3*mass(strcmp('H',symb))+mass(strcmp('O',symb))+...
    3*mass(strcmp('Fe',symb))+...
    2*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    6*(mass(strcmp('O',symb))+mass(strcmp('H',symb)));...   % (100) H3OFe3(SO4)2-6(OH)
    2*mass(strcmp('Fe',symb))+3*mass(strcmp('O',symb));...  % (101) Fe2O3
    mass(strcmp('Fe',symb))+mass(strcmp('O',symb))+...
    mass(strcmp('O',symb))+mass(strcmp('H',symb));...       % (102) FeO(OH)
    mass(strcmp('Fe',symb))+mass(strcmp('O',symb))+...
    mass(strcmp('O',symb))+mass(strcmp('H',symb));...       % (103) FeO(OH)
    mass(strcmp('Fe',symb))+mass(strcmp('O',symb))+...
    (3/4)*(mass(strcmp('O',symb))+mass(strcmp('H',symb)))+...
    (1/8)*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)));...% (104) FeO-OH(3/4)SO4(1/8)
    mass(strcmp('Fe',symb))+mass(strcmp('S',symb))+...
    4*mass(strcmp('O',symb))+...
    4*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % (105) FeSO4-4(H2O)
    2*mass(strcmp('Fe',symb))+...
    3*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    7*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % (106) Fe2(SO4)3-7H2O
    mass(strcmp('Fe',symb))+4*mass(strcmp('Fe',symb))+...
    6*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    2*(mass(strcmp('O',symb))+mass(strcmp('H',symb)))+...
    20*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% (107) Fe(Fe)4(SO4)6(OH)2-20H2O
    5*mass(strcmp('Fe',symb))+...
    6*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    mass(strcmp('O',symb))+mass(strcmp('O',symb))+mass(strcmp('H',symb))+...
    20*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% (108) Fe5(SO4)6O(OH)-20H2O
    mass(strcmp('Fe',symb))+2*mass(strcmp('Fe',symb))+...
    4*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    22*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% (109) FeFe2(SO4)4-22H2O
    mass(strcmp('Fe',symb))+2*mass(strcmp('Fe',symb))+...
    4*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    14*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% (110) FeFe2(SO4)4-14H2O
    2*mass(strcmp('K',symb))+5*mass(strcmp('Fe',symb))+...
    4*mass(strcmp('Fe',symb))+...
    12*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    18*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% (111) K2Fe5Fe4(SO4)12-(H2O)18
    mass(strcmp('Al',symb))+3*mass(strcmp('Cl',symb))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % (112) AlCl3-6H2O
    2*mass(strcmp('Al',symb))+...
    3*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    17*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% (113) Al2(SO4)3-17H2O
    mass(strcmp('Na',symb))+mass(strcmp('Br',symb));...     % (114) NaBr
    mass(strcmp('Mg',symb))+2*mass(strcmp('Br',symb));...   % (115) MgBr2
    mass(strcmp('Al',symb))+...
    3*(mass(strcmp('O',symb))+mass(strcmp('H',symb)));...   % (116) Al(OH)3
    mass(strcmp('Si',symb))+2*mass(strcmp('O',symb));...    % (117) SiO2
    mass(strcmp('Si',symb))+2*mass(strcmp('O',symb));...    % (118) SiO2
    mass(strcmp('K',symb))+3*mass(strcmp('Al',symb))+...
    2*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    6*(mass(strcmp('O',symb))+mass(strcmp('H',symb)));...   % (119) KAl3(SO4)2(OH)6
    mass(strcmp('Na',symb))+3*mass(strcmp('Al',symb))+...
    2*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    6*(mass(strcmp('O',symb))+mass(strcmp('H',symb)));...   % (120) NaAl3(SO4)2(OH)6
    mass(strcmp('K',symb))+2*mass(strcmp('Al',symb))+...
    2*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    12*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% (121) KAl2(SO4)2-12H2O
    mass(strcmp('Na',symb))+mass(strcmp('Al',symb))+...
    2*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    12*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% (122) NaAl(SO4)2-12H2O
    mass(strcmp('Fe',symb))+...
    mass(strcmp('S',symb))+4*mass(strcmp('O',symb))+...
    2*mass(strcmp('Al',symb))+...
    3*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    22*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% (123) FeSO4Al2(SO4)3-22(H2O)
    2*mass(strcmp('Al',symb))+...
    2*mass(strcmp('Si',symb))+...
    5*mass(strcmp('O',symb))+...
    4*(mass(strcmp('O',symb))+mass(strcmp('H',symb)));...   % (124) Al2Si2O5(OH)4
    mass(strcmp('Mg',symb))+...
    mass(strcmp('S',symb))+4*mass(strcmp('O',symb))+...
    2*mass(strcmp('Al',symb))+...
    3*(mass(strcmp('S',symb))+4*mass(strcmp('O',symb)))+...
    22*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...% (125) MgSO4Al2(SO4)3-22(H2O)
    mass(strcmp('Na',symb))+...
    mass(strcmp('Cl',symb))+...
    4*mass(strcmp('O',symb))+...
    2*mass(strcmp('H',symb))+mass(strcmp('O',symb));...     % (126) NaClO4-H2O
    mass(strcmp('Mg',symb))+...
    2*(mass(strcmp('Cl',symb))+4*mass(strcmp('O',symb)))+...
    8*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % (127) Mg(ClO4)2-8H2O
    mass(strcmp('Ca',symb))+...
    2*(mass(strcmp('Cl',symb))+4*mass(strcmp('O',symb)))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % (128) Ca(ClO4)2-6H2O
    mass(strcmp('K',symb))+mass(strcmp('Cl',symb))+...
    4*mass(strcmp('O',symb));...                            % (129) KClO4
    mass(strcmp('Mg',symb))+...
    2*(mass(strcmp('Cl',symb))+4*mass(strcmp('O',symb)))+...
    6*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));... % (130) Mg(ClO4)2-6H2O
    mass(strcmp('Na',symb))+...
    mass(strcmp('Cl',symb))+4*mass(strcmp('O',symb))+...
    2*(2*mass(strcmp('H',symb))+mass(strcmp('O',symb)));...  % (131) NaClO4-2H2O
    2*mass(strcmp('O',symb));...    % (151) O2 (g)
    2*mass(strcmp('O',symb));...    % (152) O2
    2*mass(strcmp('H',symb));...    % (153) H2
    mass(strcmp('C',symb))+...
    4*mass(strcmp('H',symb));...    % (154) CH4 (g)
    mass(strcmp('C',symb))+...
    4*mass(strcmp('H',symb));...    % (155) CH4
    mass(strcmp('Fe',symb))+...
    2*(mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % (156) Fe(OH)2
    mass(strcmp('Fe',symb))+...
    3*(mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % (157) Fe(OH)3 -
    mass(strcmp('Fe',symb))+...
    (mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % (158) Fe(OH)
    mass(strcmp('Fe',symb))+...
    2*(mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % (159) Fe(OH)2 +
    mass(strcmp('Fe',symb))+...
    3*(mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % (160) Fe(OH)3
    mass(strcmp('Fe',symb))+...
    4*(mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % (161) Fe(OH)4
    mass(strcmp('Al',symb))+...
    (mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % (162) Al(OH)
    mass(strcmp('Al',symb))+...
    2*(mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % (163) Al(OH)2
    mass(strcmp('Al',symb))+...
    3*(mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % (164) Al(OH)3
    mass(strcmp('Al',symb))+...
    4*(mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % (165) Al(OH)4
    mass(strcmp('Si',symb))+...
    4*(mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % (166) Si(OH)4
    mass(strcmp('Si',symb))+...
    3*(mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % (167) Si(OH)3
    nan;...                         % (168)
    mass(strcmp('B',symb))+...
    3*(mass(strcmp('O',symb))+...
    mass(strcmp('H',symb)));...     % (169) B(OH)3
    mass(strcmp('F',symb));...      % (170) F
    mass(strcmp('H',symb))+...
    mass(strcmp('F',symb));...      % (171) HF
    mass(strcmp('Sr',symb))];       % (172) Sr

% Species Molar Volume (cm^3/mol)
species.molvol = ... % @ 298 K
    [nan(30,1);... % (  1) - ( 30)
    nan;...     % ( 31) H2O (function of T)
    57.96;...   % ( 32) NaCl-2H2O
    27.02;...   % ( 33) NaCl
    37.52;...   % ( 34) KCl
    128.12;...  % ( 35) CaCl2-6H2O
    129.57;...  % ( 36) MgCl2-6H2O
    159.08;...  % ( 37) MgCl2-8H2O
    218.10;...  % ( 38) MgCl2-12H2O
    172.58;...	% ( 39) KMgCl3-6H2O
    311.81;...	% ( 40) CaCl2-2(MgCl2)-12H2O
    219.80;...  % ( 41) Na2SO4-10H2O
    53.33;...   % ( 42) Na2SO4
    132.58;...  % ( 43) MgSO4-6H2O
    146.71;...  % ( 44) MgSO4-7H2O
    65.50;...   % ( 45) K2SO4
    191.78;...  % ( 46) MgSO4-K2SO4-6H2O
    149.98;...  % ( 47) Na2SO4-MgSO4-4H2O
    74.69;...   % ( 48) CaSO4-2H2O
    45.94;...   % ( 49) CaSO4
    207.44;...  % ( 50) MgSO4-11H2O
    246.24;...  % ( 51) Na2SO4-3K2SO4
    36.93;...   % ( 52) CaCO3
    28.02;...   % ( 53) MgCO3
    74.79;...   % ( 54) MgCO3-3H2O
    100.80;...  % ( 55) MgCO3-5H2O
    117.54;...  % ( 56) CaCO3-6H2O
    38.91;...	% ( 57) NaHCO3
    198.71;...  % ( 58) Na2CO3-10H2O
    107.02;...  % ( 59) NaHCO3-Na2CO3-2H2O
    169.13;...  % ( 60) 3(MgCO3)Mg-2(OH)-3H2O
    64.34;...   % ( 61) CaMg-2(CO3)
    153.71;...  % ( 62) Na2CO3-7H2O
    46.14;...   % ( 63) KHCO3
    34.15;...   % ( 64) CaCO3
    37.72;...   % ( 65) CaCO3
    73.09;...   % ( 66) HNO3-3H2O
    48.04;...   % ( 67) KNO3
    37.60;...   % ( 68) NaNO3
    62.51;...   % ( 69) HCl-3H2O
    154.86;...  % ( 70) H2SO4-6.5H2O
    113.98;...  % ( 71) H2SO4-4H2O
    101.06;...  % ( 72) HCl-6H2O
    119.57;...  % ( 73) NaNO3-Na2SO4-2H2O
    nan;...     % ( 74) Na3H(SO4)2
    65.65;...   % ( 75) NaHSO4-H2O
    nan;...     % ( 76) K3H(SO4)2
    nan;...     % ( 77) K5H3(SO4)4
    nan;...     % ( 78) K8H6(SO4)7-H2O
    58.64;...   % ( 79) KHSO4
    56.60;...   % ( 80) MgSO4-H2O
    146.48;...  % ( 81) FeSO4-7(H2O)
    57.21;...   % ( 82) FeSO4-H2O
    133.65;...  % ( 83) FeCl2-6H2O
    103.01;...  % ( 84) FeCl2-4H2O
    30.49;...   % ( 85) FeCO3
    28.12;...   % ( 86) Fe(OH)3
    135.75;...  % ( 87) CO2-6(H2O)
    135.75;...  % ( 88) CH4-6(H2O)
    207.59;...  % ( 89) FeCl3-10H2O
    146.90;...  % ( 90) FeCl3-6H2O
    138.84;...  % ( 91) FeCl3-2KCl-H2O
    129.12;...  % ( 92) Fe2(SO4)3
    406.95;...  % ( 93) Fe2(SO4)3-2(K2SO4)14H2O
    184.01;...  % ( 94) K2SO4FeSO46H2O
    162.23;...  % ( 95) Na2SO4FeSO4-4H2O
    267.63;...  % ( 96) Fe2(SO4)3-9H2O
    295.61;...  % ( 97) Fe2(SO4)3-H2SO4-8H2O
    162.07;...  % ( 98) KFe3-(SO4)2-6(OH)
    156.86;...  % ( 99) NaFe3(SO4)2-6(OH)
    178.05;...  % (100) H3OFe3(SO4)2-6(OH)
    30.48;...   % (101) Fe2O3
    20.76;...   % (102) FeO(OH)
    22.21;...   % (103) FeO(OH)
    24.90;...   % (104) FeO-OH(3/4)SO4(1/8)
    99.10;...   % (105) FeSO4-4(H2O)
    228.10;...  % (106) Fe2(SO4)3-7H2O
    595.21;...  % (107) Fe(Fe)4(SO4)6(OH)2-20H2O
    594.71;...  % (108) Fe5(SO4)6O(OH)-20H2O
    507.02;...  % (109) FeFe2(SO4)4-22H2O
    373.96;...  % (110) FeFe2(SO4)4-14H2O
    762.15;...  % (111) K2Fe5Fe4(SO4)12-(H2O)18
    144.57;...  % (112) AlCl3-6H2O
    379.19;...  % (113) Al2(SO4)3-17H2O
    nan;...     % (114) NaBr
    nan;...     % (115) MgBr2
    33.33;...   % (116) Al(OH)3
    22.93;...   % (117) SiO2
    22.93;...   % (118) SiO2
    151.17;...  % (119) KAl3(SO4)2(OH)6
    144.77;...  % (120) NaAl3(SO4)2(OH)6
    269.54;...  % (121) KAl2(SO4)2-12H2O
    264.90;...  % (122) NaAl(SO4)2-12H2O
    483.91;...  % (123) FeSO4Al2(SO4)3-22(H2O)
    99.29;...   % (124) Al2Si2O5(OH)4
    471.90;...  % (125) MgSO4Al2(SO4)3-22(H2O)
    69.53;...   % (126) NaClO4-H2O
    189.43;...  % (127) Mg(ClO4)2-8H2O
    156.47;...  % (128) Ca(ClO4)2-6H2O
    54.98;...   % (129) KClO4
    167.32;...  % (130) Mg(ClO4)2-6H2O
    85.00;...   % (131) NaClO4-2H2O
    nan(172-151+1,1)]; % (151) - (172)

% Species Density (g/cm^3)
species.rho = species.mass./species.molvol;

%% Read-In File
k_solid_tot = length(31:131); % solid species count (independent of input file)
solid_species_mass = species.mass(ismember(species.num,31:131));
rho_solid_species = species.rho(ismember(species.num,31:131));

% Find number of solution species
fid = fopen(fn);
k_solut = 0; % solution species count (dependent on input file)
k_temp = 0; % output temperature count
n = 0;
tline = fgetl(fid);
while ischar(tline)
    tline = fgetl(fid);
    if ~isempty(tline) & tline~=-1
        if contains(tline,' Temp(K)')
            n = n + 1;
            tline = fgetl(fid);
            data = sscanf(tline,'%f %f %f %f %f %f %f');
            if data(5)<0 % catch for negative H2O
                break
            end
        elseif contains(tline,' Solution')
            k_temp = k_temp +1;
            tline = fgetl(fid);
            if k_solut == 0
                while ~isempty(tline)
                    tline = fgetl(fid);
                    if ~contains(tline,'(BAR)') && ~contains(tline,'(L)')
                        k_solut = k_solut + 1;
                    end
                end
            end
            k_solut_tot(n) = k_solut - 1;
            k_solut = 0;
        elseif contains(tline,'SOLIDS') | contains(tline,'AT T =')
            if contains(tline,'SOLIDS')
                ind = strfind(tline,'PRECIPITATING');
                tline_solids = tline(ind+length('PRECIPITATING ARE'):end);
                solids = sscanf(tline_solids,'%d');
            end
            if contains(tline,'AT T =')
                ind = strfind(tline,'AT T =');
                tline_temp = tline(ind+length('AT T ='):ind+length('AT T =')+7);
                Teut = sscanf(tline_temp,'%f');
            end
        end
    end
end
fclose(fid);
k_solut_tot_max = max(k_solut_tot);

% Pre-allocate
FrOut.T = zeros(k_temp,1); % Temperatures (K)
FrOut.ion_str = FrOut.T; % Ionic Strength
FrOut.rho_b = FrOut.T; % Brine Density (g/cm^3)
FrOut.osmotic_coef = FrOut.T; % Osmotic Coefficient
FrOut.br_H2O = FrOut.T; % Mass of Water in Brine (g)
FrOut.ice_H2O = FrOut.T; % Mass of Water in Ice (g)
FrOut.pressure = FrOut.T; % Pressure (bar)
FrOut.br_salt = FrOut.T; % Mass of Salt (Ions) in Brine (g)
FrOut.sm = FrOut.T; % Mass of Solid Salt (Hydrates) in Brine
FrOut.rho_ss = FrOut.T; % Total Density of Solid Salt (Hydrates)
FrOut.H2O_activity = FrOut.T; % Water Activity

FrOut.solution_species = cell(k_temp,k_solut_tot_max); % Solution Species (Ions)
FrOut.init_conc = zeros(k_temp,k_solut_tot_max); % Initial Concentration (moles/kg)
FrOut.final_conc = FrOut.init_conc; % Final Concentration(moles/kg)
FrOut.activity_coef = FrOut.init_conc; % Activity Coefficient
FrOut.activity = FrOut.init_conc; % Activity
FrOut.solution_moles = FrOut.init_conc; % Moles of Solution Species (moles)
FrOut.mass_balance = FrOut.init_conc; % Mass of Major Species (moles/kg)

FrOut.solid_species = cell(k_temp,k_solid_tot); % Solid Species (Hydrates)
FrOut.solid_moles = zeros(k_temp,k_solid_tot); % Solid Moles
FrOut.equil_const = FrOut.solid_moles; % Equilibrium Constant
FrOut.accum_moles = FrOut.solid_moles; % Accumulated Moles

% Solid vs Accumulated Moles:
% For equilibrium crystallization, accumulated moles = solid moles. For
% fractional crystallization accumulated moles >= solid moles. For
% fractional crystallization, solid moles represents the solids that have
% precipitated in the last interval.

% Extract data
fid = fopen(fn);
n = 0;
tline = fgetl(fid);
while ischar(tline)
    tline = fgetl(fid);
    if ~isempty(tline) & tline~=-1
        if contains(tline,'TITLE')
            n = n+1; % output count
        elseif contains(tline,' Temp(K)')
            data = fscanf(fid,'%f %f %f %f %f %f %f');
            if data(5)<0 % catch for negative H2O
                break
            end
            FrOut.T(n) = data(1); % K
            FrOut.ion_str(n) = data(2);
            FrOut.rho_b(n) = data(3); % g/cm^3
            FrOut.osmotic_coef(n) = data(4);
            FrOut.br_H2O(n) = data(5); % g
            FrOut.ice_H2O(n) = data(6); % g
            FrOut.pressure(n) = data(7); % bar
        elseif contains(tline,'Solution')
            k_solut = 0;
            tline = fgetl(fid);
            while k_solut < k_solut_tot(n)
                data = textscan(fid,'%s %f %f %f %f %f %f',1);
                if ~contains(data{1},'(BAR)') && ~contains(data{1},'(L)')
                    k_solut = k_solut + 1;
                    FrOut.solution_species(n,k_solut) = data{1}; % name
                    FrOut.init_conc(n,k_solut) = data{2}; % moles/kg
                    FrOut.final_conc(n,k_solut) = data{3}; % moles/kg
                    FrOut.activity_coef(n,k_solut) = data{4};
                    FrOut.activity(n,k_solut) = data{5};
                    FrOut.solution_moles(n,k_solut) = data{6}; % moles
                    FrOut.mass_balance(n,k_solut) = data{7}; % moles/kg
                end
            end
            
            ind = cellfun(@isempty,FrOut.solution_species(n,:));
            ind0 = ~ind;
            
            [~,ind] = ismember(FrOut.solution_species(n,ind0),species.str);
            solution_species_mass = species.mass(ind);
            
            % mass of salt (ions) in brine
            FrOut.br_salt(n) = sum(FrOut.solution_moles(n,ind0)'.*solution_species_mass);
        
        elseif contains(tline,'H2O') && contains(tline,'(L)')
            FrOut.H2O_activity(n) = sscanf(tline,'%*s %*f %f %*f %*f');
            
        elseif contains(tline,' Solid')
            tline = fgetl(fid);
            data = textscan(fid,'%s %f %f %f',length(solid_species_mass));
            FrOut.solid_species(n,:) = data{1}; % name
            FrOut.solid_moles(n,:) = data{2}; % moles
            FrOut.equil_const(n,:) = data{3};
            FrOut.accum_moles(n,:) = data{4}; % moles
            
            if length(ismember(FrOut.solid_species(n,:),species.str))~=length(FrOut.solid_species(n,:))
                error('FREZCHEM output contains unknown solid species.')
            end
            
            ice_H2O_check=FrOut.solid_moles(n,1)*solid_species_mass(1);
            if abs(FrOut.ice_H2O(n)-ice_H2O_check)>0.1
                error('Discrepancy between mass and moles of H2O in output.')
            end
            
            % mass of solid salts (hydrates) in brine
            FrOut.sm(n) = sum(FrOut.solid_moles(n,2:end)'.*solid_species_mass(2:end));
            
            % mass of solid solids with defined molar volume
            ind = find(~isnan(rho_solid_species(2:end)))+1;
            sm = sum(FrOut.solid_moles(n,ind)'.*solid_species_mass(ind));
            
            if sm==0
                FrOut.rho_ss(n) = nan;
            else
                ind = find(FrOut.solid_moles(n,2:end)>0);
                ind = ind + 1;
                 FrOut.rho_ss(n) = nansum(FrOut.solid_moles(n,ind)'.*...
                     solid_species_mass(ind))/nansum((FrOut.solid_moles(n,ind)'.*...
                     solid_species_mass(ind))./rho_solid_species(ind));
                if isnan(FrOut.rho_ss(n))
                end
            end
        end
    end
end
fclose(fid);

disp(['Solids precipitating at T >= ',num2str(min(FrOut.T)),' K'])
ind = find(max(FrOut.solid_moles)>0);
solids_str = FrOut.solid_species(1,ind);
solids_num = species.num(ismember(species.str,solids_str));
solids_disp = [num2cell(solids_num)'; solids_str];
text1 = sprintf('%3d %s\n',solids_disp{:});
fprintf('%s',text1);

if exist('solids','var')
    solids_str = species.str(ismember(species.num,solids));
    solids_disp = [num2cell(solids)'; solids_str'];
    text1 = sprintf(['Solids precipitating at T = ',num2str(Teut),' K']);
    text2 = sprintf('%3d %s\n',solids_disp{:});
    msg = sprintf('%s\n%s',text1,text2);
    disp(msg)
    
    FrOut.eutectic.Teut = Teut;
    FrOut.eutectic.solid_species = solids_str';
    rho_ss_eut = species.rho(ismember(species.num,solids));
    
    rho_ss_eut = rho_ss_eut(2:end);
    solid_species_final = solids_str(2:end);
    ind =  cellfun(@isempty,FrOut.solution_species(end,:));
    solution_species_final = FrOut.solution_species(end,~ind);
    solution_species_ignore = [];
    if any(contains(solution_species_final,'H')) && any(contains(solution_species_final,'OH'))
        solution_species_ignore = find(strcmp(solution_species_final,'H') | strcmp(solution_species_final,'OH'));
    end
    if any(contains(solution_species_final,'CO2'))
        solution_species_final{strcmp(solution_species_final,'CO2')} = 'H2CO3*';
    end
    solution_species_final(solution_species_ignore) = [];
    solution_moles_final = FrOut.solution_moles(end,~ind);
    solution_moles_final(solution_species_ignore) = [];
    [solution_moles_sorted, ind] = sort(solution_moles_final,'descend');
    solution_species_sorted = solution_species_final(ind);
    solid_molar_mass_final = zeros(length(solid_species_final),1);
    
    
    
    % Carbonates
    if any(contains(solution_species_final,'CO3'))
        ind = find(contains(solution_species_sorted,'CO3'));
        CT_C = sum(solution_moles_sorted(ind));
        solution_species_sorted(ind(2:end)) = [];
        solution_moles_sorted(ind(2:end)) = [];
        solution_moles_sorted(ind(1)) = CT_C;
        solution_species_sorted{ind(1)} = 'CO3';
    end
    
    % Silicates
    if any(contains(solution_species_final,'SI'))
        ind = find(contains(solution_species_sorted,'SI'));
        CT_SI = sum(solution_moles_sorted(ind));
        solution_species_sorted(ind(2:end)) = [];
        solution_moles_sorted(ind(2:end)) = [];
        solution_moles_sorted(ind(1)) = CT_SI;
        solution_species_sorted{ind(1)} = 'SI';
    end
    
    % Borates
    if any(contains(solution_species_final,'B'))
        ind = find(contains(solution_species_sorted,'B'));
        for n = 1:length(ind)
            if strcmp(solution_species_sorted{ind(n)},'BR')
                ind(n) = NaN;
            end
        end
        ind(isnan(ind)) = [];
        CT_B = sum(solution_moles_sorted(ind));
        solution_species_sorted(ind(2:end)) = [];
        solution_moles_sorted(ind(2:end)) = [];
        solution_moles_sorted(ind(1)) = CT_B;
        solution_species_sorted{ind(1)} = 'B';
    end
    ind = find(contains(solid_species_final,'B') & ~contains(solid_species_final,'BR'));
    if isempty(ind)
        solution_moles_sorted(strcmp(solution_species_sorted,'B')) = [];
        solution_species_sorted(strcmp(solution_species_sorted,'B')) = [];
    end
    
    % Fluoride species
    if any(contains(solution_species_final,'F'))
        ind = find(contains(solution_species_sorted,'F'));
        CT_F = sum(solution_moles_sorted(ind));
        solution_species_sorted(ind(2:end)) = [];
        solution_moles_sorted(ind(2:end)) = [];
        solution_moles_sorted(ind(1)) = CT_F;
        solution_species_sorted{ind(1)} = 'F';
    end
    
    % Sulfate species
    if any(contains(solution_species_final,'SO4'))
        ind = find(contains(solution_species_sorted,'SO4'));
        CT_SO4 = sum(solution_moles_sorted(ind));
        solution_species_sorted(ind(2:end)) = [];
        solution_moles_sorted(ind(2:end)) = [];
        solution_moles_sorted(ind(1)) = CT_SO4;
        solution_species_sorted{ind(1)} = 'SO4';
    end
    
    % Magnesium species
    if any(contains(solution_species_final,'MG'))
        ind = find(contains(solution_species_sorted,'MG'));
        CT_MG = sum(solution_moles_sorted(ind));
        solution_species_sorted(ind(2:end)) = [];
        solution_moles_sorted(ind(2:end)) = [];
        solution_moles_sorted(ind(1)) = CT_MG;
        solution_species_sorted{ind(1)} = 'MG';
    end
    
    solution_in_solid = zeros(length(solid_species_final),length(solution_species_sorted));
    for n = 1:length(solid_species_final)
        solid_molar_mass_final(n) = species.mass(strcmp(solid_species_final{n},species.str));
        for m = 1:length(solution_species_sorted)
            ind = strfind(solid_species_final{n},solution_species_sorted{m});
            if isempty(ind)
                solution_in_solid(n,m) = 0;
            else
                if (ind+length(solution_species_sorted{m}))>length(solid_species_final{n})
                    solution_in_solid(n,m) = 1;
                elseif strcmp((ind+length(solution_species_sorted{m})+1),'(')
                    solution_in_solid(n,m) = str2double(solid_species_final{n}(ind+length(solution_species_sorted{m})+2));
                else
                    [num, status] = str2num(solid_species_final{n}(ind+length(solution_species_sorted{m})));
                    if status
                        solution_in_solid(n,m) = num;
                    else
                        solution_in_solid(n,m) = 1;
                    end
                end
            end
        end
    end
    
    ind = find(all(solution_in_solid==0));
    solution_in_solid(:,ind) = [];
    solution_moles_sorted(ind) = [];
    
    [m,n] = size(solution_in_solid);
    if m==n
        if det(solution_in_solid')==0
            solid_moles_final = pinv(solution_in_solid')*solution_moles_sorted';
        else
            solid_moles_final = solution_in_solid'\solution_moles_sorted';
        end
    else
        solid_moles_final = solution_in_solid'\solution_moles_sorted';
    end
    if any(solid_moles_final<0)
        opts = optimset('display','off');
        [solid_moles_final,~,~,exitflag,~,~] = lsqlin(solution_in_solid',solution_moles_sorted',...
            -eye(length(solid_species_final)),zeros(length(solid_species_final),1),[],[],[],[],[],opts);
        if exitflag~=1
            warning(['Constrained optimization failed for assigning final salt mass, removing',...
                ' constraint for positive mass of precipitating solids.'])
            if m==n
                if det(solution_in_solid')==0
                    solid_moles_final = pinv(solution_in_solid')*solution_moles_sorted';
                else
                    solid_moles_final = solution_in_solid'\solution_moles_sorted';
                end
            else
                solid_moles_final = solution_in_solid'\solution_moles_sorted';
            end
        end
    end
    
    solid_mass_final = sum(solid_moles_final.*solid_molar_mass_final);
    FrOut.eutectic.sm = FrOut.sm(end)+solid_mass_final;
    if isnan(FrOut.eutectic.sm)
        warning('Failed to assign final salt mass beyond the eutectic.')
    end
    
    FrOut.eutectic.rho_ss = nansum(solid_moles_final.*solid_molar_mass_final)/...
        nansum((solid_moles_final.*solid_molar_mass_final)./rho_ss_eut);
    if ~isnan(FrOut.rho_ss(end))
        rho1 = FrOut.eutectic.rho_ss;
        m1 = nansum((solid_moles_final.*solid_molar_mass_final));
        
        rho2 = FrOut.rho_ss(end);
        m2 = FrOut.sm(end);
        
        FrOut.eutectic.rho_ss = (m1+m2)/((m1/rho1)+(m2/rho2));
    end
else
    warning(['No solids precipitating at final temperature step, ',...
        'your FREZCHEM file has either not reached the eutectic, ',...
        'output a negative mass of H2O, ',...
        ' or your compiled version fails to print this text.'])
    FrOut.eutectic.Teut = NaN;
    FrOut.eutectic.solid_species = NaN;
    FrOut.eutectic.sm = NaN;
    FrOut.eutectic.rho_ss = NaN;
end
end

